### ISSUE TITLE
Can't assign myself as a texter

### ISSUE THREAD

**Issue by dev-mcm** [SalazarForSenate/Spoke#1]
Oddly I can't seem to assign myself as a texter when creating a new campaign, although I can create a dynamic link and then follow the link to send texts after creating the campaign

# I don't show up when I type in my name
![image](https://user-images.githubusercontent.com/6991397/40673914-3f575a58-6341-11e8-812d-b6b04bd7ea22.png)

# only Harpo shows up when I click "add all"
![image](https://user-images.githubusercontent.com/6991397/40673869-1f9c39fe-6341-11e8-8959-9c479f2febab.png)

**Comment by harpojaeger** [comment]
@dev-mcm was this resolved, do I recall?
